<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shumway.Core\Shumway.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>$(ShumwayTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
