using System.Text;
using System.Text.RegularExpressions;
using Shumway.Builtins;

namespace Shumway.Embedding;

/// <summary>
/// Generates the user-facing predicate reference (<c>docs/predicates.md</c>)
/// from the predicate definitions themselves, so it never drifts.
///
/// <para>Two metadata sources, both living next to the definition:</para>
/// <list type="bullet">
/// <item>C# builtins carry a category and summary passed to
/// <see cref="BuiltinsRegistry.Register"/>; internal <c>$</c>-named helpers
/// leave them null and are skipped.</item>
/// <item>Prolog library predicates (the prelude and CLP(FD)) carry a
/// structured <c>%! name/arity | Category | Summary</c> comment in their
/// source.</item>
/// </list>
///
/// <para>A unit test regenerates the document and fails if the committed copy
/// is stale; running the suite with the <c>SHUMWAY_REGEN_DOCS</c> environment
/// variable set rewrites it. As predicates are added or changed the reference
/// is regenerated, never hand-edited.</para>
/// </summary>
public static class PredicateDoc
{
    private sealed record Entry(string Category, string Name, int Arity, string Summary);

    /// <summary>Matches a <c>%! name/arity | Category | Summary</c> comment.
    /// The name may itself contain <c>/</c> (operator atoms such as
    /// <c>#/\</c>), so the arity is taken as the final <c>/digits</c>.</summary>
    private static readonly Regex DocComment = new(
        @"^\s*%!\s*(.+)/(\d+)\s*\|\s*([^|]+?)\s*\|\s*(.+?)\s*$",
        RegexOptions.Compiled);

    /// <summary>Preferred section order. Categories not listed here are
    /// emitted after these, in alphabetical order.</summary>
    private static readonly string[] CategoryOrder =
    {
        "Unification & comparison",
        "Type checking",
        "Arithmetic",
        "Term ordering",
        "Term inspection & construction",
        "Control",
        "Findall & aggregation",
        "Database",
        "Lists",
        "Atoms & strings",
        "Attributed variables",
        "Input / output",
        "Flags, operators & reflection",
        "CLP(FD) — domains",
        "CLP(FD) — arithmetic constraints",
        "CLP(FD) — global constraints",
        "CLP(FD) — labeling",
        "CLP(FD) — reification",
    };

    /// <summary>Builds the predicate-reference markdown. Newlines are
    /// always <c>\n</c> so the result is comparable across platforms.</summary>
    public static string Generate()
    {
        StandardBuiltins.EnsureRegistered();
        MetaBuiltins.EnsureRegistered();

        var entries = new List<Entry>();
        foreach (var b in BuiltinsRegistry.AllEntries())
            if (b.Category is not null && b.Summary is not null && !b.Name.StartsWith('$'))
                entries.Add(new Entry(b.Category, b.Name, b.Arity, b.Summary));
        CollectDocComments(Prelude.Source, entries);
        CollectDocComments(Clpfd.Source, entries);

        return Render(entries);
    }

    private static void CollectDocComments(string source, List<Entry> into)
    {
        foreach (var line in source.Split('\n'))
        {
            Match m = DocComment.Match(line);
            if (!m.Success) continue;
            into.Add(new Entry(
                m.Groups[3].Value.Trim(),
                m.Groups[1].Value.Trim(),
                int.Parse(m.Groups[2].Value),
                m.Groups[4].Value.Trim()));
        }
    }

    private static string Render(List<Entry> entries)
    {
        var sb = new StringBuilder();
        sb.Append("# Shumway predicate reference\n\n");
        sb.Append("_Generated by `Shumway.Embedding.PredicateDoc` — do not edit by hand._\n");
        sb.Append("_Regenerate by running the test suite with the `SHUMWAY_REGEN_DOCS` ");
        sb.Append("environment variable set._\n\n");
        sb.Append("Predicates available to programs embedding Shumway, grouped by area. ");
        sb.Append("The CLP(FD) sections require the constraint library to be loaded with ");
        sb.Append("`engine.UseClpfd()`.\n");

        foreach (string category in OrderedCategories(entries))
        {
            sb.Append("\n## ").Append(category).Append("\n\n");
            sb.Append("| Predicate | Description |\n");
            sb.Append("| --- | --- |\n");
            IEnumerable<Entry> inCategory = entries
                .Where(e => e.Category == category)
                .OrderBy(e => e.Name, StringComparer.Ordinal)
                .ThenBy(e => e.Arity);
            foreach (Entry e in inCategory)
                sb.Append("| `").Append(e.Name).Append('/').Append(e.Arity)
                  .Append("` | ").Append(e.Summary.Replace("|", "\\|")).Append(" |\n");
        }
        return sb.ToString();
    }

    private static IEnumerable<string> OrderedCategories(List<Entry> entries)
    {
        var present = entries.Select(e => e.Category).ToHashSet();
        foreach (string c in CategoryOrder)
            if (present.Remove(c)) yield return c;
        foreach (string c in present.OrderBy(c => c, StringComparer.Ordinal))
            yield return c;
    }
}
