using Shumway.Embedding;
using Xunit;

namespace Shumway.Tests.Embedding;

/// <summary>
/// Phase 14 chunk 169: <c>shumway-compile</c> accepts
/// <c>--debug</c> / <c>--release</c> flags. Default is release.
/// The chosen mode is recorded into the V2
/// <c>.shmo</c> via <see cref="ShmoObject.BuildMode"/>; the linker
/// surfaces it in the chunk-173 map file and the chunk-172
/// <c>--strip</c> path can branch on it.
/// </summary>
public class Chunk169Tests
{
    [Fact]
    public void DefaultMode_IsRelease()
    {
        var obj = ShmoCompiler.CompileSource(":- module(m).\np(1).\n");
        Assert.Equal(ShmoBuildMode.Release, obj.BuildMode);
    }

    [Fact]
    public void DebugMode_PropagatesIntoShmoObject()
    {
        var obj = ShmoCompiler.CompileSource(
            ":- module(m).\np(1).\n",
            moduleNameFallback: "m",
            buildMode: ShmoBuildMode.Debug);
        Assert.Equal(ShmoBuildMode.Debug, obj.BuildMode);
    }

    [Fact]
    public void BuildMode_RoundTripsThroughShmoIo()
    {
        var release = ShmoCompiler.CompileSource(":- module(m).\np(1).\n",
            buildMode: ShmoBuildMode.Release);
        var debug = ShmoCompiler.CompileSource(":- module(m).\np(1).\n",
            buildMode: ShmoBuildMode.Debug);

        var restoredRelease = ShmoReader.FromBytes(ShmoWriter.ToBytes(release));
        var restoredDebug = ShmoReader.FromBytes(ShmoWriter.ToBytes(debug));

        Assert.Equal(ShmoBuildMode.Release, restoredRelease.BuildMode);
        Assert.Equal(ShmoBuildMode.Debug, restoredDebug.BuildMode);
    }

    [Fact]
    public void ShmoFormat_VersionIsFrozen_NoBackCompat()
    {
        // Pre-release format policy (chunk 412, per project decision): exactly
        // ONE supported layout, frozen version number, no backward
        // compatibility and no version bumps until the first public release —
        // stale .shmo files are regenerated by recompiling.
        Assert.Equal(3, ShmoFormat.CurrentVersion);
        Assert.Equal(ShmoFormat.CurrentVersion, ShmoFormat.MinSupportedVersion);
    }

    [Fact]
    public void OlderVersionNumber_IsRejected()
    {
        // Pre-release: no back-compat readers. Any version number other than
        // the frozen current one is rejected with a recompile hint.
        var obj = ShmoCompiler.CompileSource("p.\n");
        byte[] bytes = ShmoWriter.ToBytes(obj);
        bytes[4] = 1; bytes[5] = 0; bytes[6] = 0; bytes[7] = 0;   // version := 1
        var ex = Assert.Throws<InvalidDataException>(() => ShmoReader.FromBytes(bytes));
        Assert.Contains("recompile", ex.Message);
    }

    [Fact]
    public void UnsupportedFutureVersion_Throws()
    {
        var obj = ShmoCompiler.CompileSource("p.\n");
        byte[] bytes = ShmoWriter.ToBytes(obj);
        // Bump version to 999.
        bytes[4] = 0xE7;
        bytes[5] = 0x03;
        bytes[6] = 0x00;
        bytes[7] = 0x00;
        var ex = Assert.Throws<InvalidDataException>(() => ShmoReader.FromBytes(bytes));
        Assert.Contains("999", ex.Message);
    }
}
