<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shumway.Core\Shumway.Core.csproj" />
    <ProjectReference Include="..\Shumway.Compiler\Shumway.Compiler.csproj" />
    <ProjectReference Include="..\Shumway.Embedding\Shumway.Embedding.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>shumway-link</AssemblyName>
    <RootNamespace>Shumway.Link</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
