<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shumway.Core\Shumway.Core.csproj" />
    <ProjectReference Include="..\Shumway.Compiler\Shumway.Compiler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sigil" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Shumway.Tests.Embedding" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
